name: bookstore
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  email_auth: ^2.0.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^4.0.3
  lottie: ^3.2.0
  curved_navigation_bar: ^1.0.3
  get_storage: ^2.0.3
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  google_sign_in: ^6.2.2
  flutter_cube: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/models/
    - assets/models/book.obj
    - assets/models/books.mtl
    - assets/models/book1.png
    - assets/models/book2.png
    - assets/models/book3.png
    - assets/models/book4.png
    - assets/models/book5.png
    - assets/models/book6.png
    - assets/models/book7.png
    - assets/models/book8.png
    - assets/animations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
